from .Photon import Photon
from QKD_Algorithms_OLD.Logger import SimLogger
from random import random

logger = SimLogger()


class Source:

    def __init__(self, n: int = 2, p: float = 1.0):
        """
        :param n: How many photons are generated by source each time
        :param p: probability of entanglement, if generated photons are enatgled they are 00... + 11...,
            if not, the are all 0 + 1 (normalised)
        """
        self.n: int = n
        self.p = p

    def generate(self):
        r : float = random()
        photons: list[Photon] = [Photon() for _ in range(self.n)]

        if r <= self.p:
            for ph in photons:
                ph.entangle(photons)

        return tuple(photons)
