from Logger import SimLogger
from .PhotonE91 import PhotonE91 as Photon
from .PhotonE91 import EntanglemetController
from random import random


class Source:
    def __init__(self, logger: SimLogger, photon_factory, controller_factory: EntanglemetController,
                 n: int = 2, distribution: list[tuple[float, [list[float]]]] | None = None):
        """
        :param n: How many photons are generated by source each time
        :param distribution: list of tuples (q, [p0, p1, ..., p_{2**n - 1}])
            Where sum of ps in each list is 1 (probabilities of generating photon states (binary represntation)
            Sum of q (bby tuples) is 1 - probability that generated photons are entangled in given way
            By default None - equal to (1, [1/2, 0, 0, ..., 0, 1/2]) - perfectly enatgled phtons in states 000... and 111... (50/50)
        """
        self.logger = logger
        self.photon_factory = photon_factory
        self.controller_factory = controller_factory

        self.n: int = n
        self.distribution: list[tuple[float, [list[float]]]] = []

        if distribution:
            if abs(sum([ent[0] for ent in distribution]) - 1.0) > 1e-10:
                raise ValueError("Probabilities of possible entanglements do not sum to 1!")

            for (i, ent) in enumerate(distribution):
                if abs(sum(ent[1]) - 1.0) > 1e-10:
                    raise ValueError(f"Probabilities of possible states in entanglement {i} do not sum to 1!")

                if len(ent[1]) != 2 ** n:
                    raise ValueError(
                        f"Wrong number of states in entanglement {i}! (Should be {2 ** n}, is {len(ent[1])})")

            self.distribution = distribution

        else:
            self.distribution = [(1.0, [0.0 for _ in range(2 ** n)])]
            self.distribution[0][1][0] = 0.5
            self.distribution[0][1][-1] = 0.5

    def roll_for_distribution(self):
        r: float = random()
        s: float = 0.0

        for ent in self.distribution:
            s += ent[0]

            if r <= s:
                return ent[1]

    def generate(self):
        photons: list[Photon] = [self.photon_factory() for _ in range(self.n)]
        controller: EntanglemetController = self.controller_factory(photons, self.roll_for_distribution())
        # controller adds itself as reference to each photon - do not remove

        return tuple(photons)
